### PR TITLE
feat: added tailwind css

### LINKED ISSUE #4: feat: Add Tailwind CSS
https://tailwindcss.com/docs/guides/vite

FOLLOW THE ABOVE DOC TO INSTALL TAILWIND IN THIS PROJECT.

### PR DESCRIPTION
**Pull request by Vaishali785**
fixes #4

### CODE REVIEW

**Review by dakshsinghrathore — APPROVED** [review]
Looks good to me 🙌🏼

**Comment by dakshsinghrathore** [comment]
Hey @Vaishali785, kindly fix the conflicting files, and you are good to go.
update the package.json with the below versions.
```JSON 
    "autoprefixer": "^10.4.20",
    "eslint": "^9.13.0",
    "eslint-plugin-react": "^7.37.2",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-react-refresh": "^0.4.13",
 ```

**Comment by Vaishali785** [comment]
> Hey @Vaishali785, kindly fix the conflicting files, and you are good to go. update the package.json with the below versions.
> 
> ```json
>     "autoprefixer": "^10.4.20",
>     "eslint": "^9.13.0",
>     "eslint-plugin-react": "^7.37.2",
>     "eslint-plugin-react-hooks": "^5.0.0",
>     "eslint-plugin-react-refresh": "^0.4.13",
> ```

I've updated these packages, please check again.

**Comment by dakshsinghrathore** [comment]
@Vaishali785 sure, resolve here .

**Comment by Vaishali785** [comment]
> @Vaishali785 sure, resolve here .

done.

**Review by dakshsinghrathore — APPROVED** [review]

**Pull request merged**
