### PR TITLE
Feat: Add CI/CD Workflow for enabling linting.

### PR DESCRIPTION
**Pull request by KrinsKumar**
This PR addresses #7 

One new file was added in a new directory called .github
- .github/workflows/lint.yml - contains a github action script that would lint the code when a PR is made.

I am not really sure on how we can test this before merging.😭

Let me know if there are any questions or further adjustments needed.

### CODE REVIEW

**Comment by KrinsKumar** [comment]
I have few suggestions with regards to this change.
- We can added prettier or something similar in this workflow so that we can make sure that the code is consistent.
- We can also make this file more PR oriented as opposed to linting oriented where we add tests as well.

**Review by dakshsinghrathore — CHANGES_REQUESTED** [review]
Some changes I would like you to make !
- **Use the latest versions of the actions**: Consider updating the checkout and setup-node actions to the latest versions (v3) for improved performance and features.
- Switch from `npm install` to `npm ci` for faster and more consistent dependency installation.
- Add caching with `cache: 'npm'`

**Comment by KrinsKumar** [comment]
Done!, is there a way we can test this before merging?

**Review by dakshsinghrathore — APPROVED** [review]
Looks good to me 🙌🏼

**Comment by dakshsinghrathore** [comment]
@KrinsKumar Yes, you can test your GitHub Action before merging by running it in a **draft pull request* or a pull request against a non-production branch (e.g., `develop` or a temporary testing branch).

**Pull request merged**
